-- NihonGO Japanese Learning Platform
-- Supabase Database Schema (Normalized)
-- Run this in Supabase SQL Editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- Table: jlpt_levels (Reference Table)
-- ============================================
CREATE TABLE IF NOT EXISTS jlpt_levels (
  id VARCHAR(2) PRIMARY KEY, -- 'N5', 'N4', 'N3', 'N2', 'N1'
  name VARCHAR(50) NOT NULL,
  description TEXT,
  difficulty_order INTEGER NOT NULL, -- 5=easiest, 1=hardest
  target_vocabulary INTEGER, -- Target vocab count
  target_kanji INTEGER, -- Target kanji count
  estimated_hours INTEGER, -- Estimated study hours
  color VARCHAR(7), -- Hex color for UI
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert JLPT levels data (seeder)
INSERT INTO jlpt_levels (id, name, description, difficulty_order, target_vocabulary, target_kanji, estimated_hours, color) VALUES
  ('N5', 'JLPT N5 - Pemula', 'Kemampuan memahami bahasa Jepang dasar', 5, 800, 100, 150, '#22C55E'),
  ('N4', 'JLPT N4 - Dasar', 'Kemampuan memahami bahasa Jepang sehari-hari', 4, 1500, 300, 300, '#3B82F6'),
  ('N3', 'JLPT N3 - Menengah', 'Kemampuan memahami bahasa Jepang dalam berbagai situasi', 3, 3750, 650, 450, '#8B5CF6'),
  ('N2', 'JLPT N2 - Lanjutan', 'Kemampuan memahami bahasa Jepang dalam berbagai topik', 2, 6000, 1000, 600, '#F59E0B'),
  ('N1', 'JLPT N1 - Mahir', 'Kemampuan memahami bahasa Jepang kompleks', 1, 10000, 2000, 900, '#EF4444')
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- Table: categories (Reference Table)
-- ============================================
CREATE TABLE IF NOT EXISTS categories (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  slug VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  content_type VARCHAR(20) CHECK (content_type IN ('kanji', 'kosakata', 'bunpo')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default categories (seeder)
INSERT INTO categories (slug, name, content_type) VALUES
  -- Kanji categories
  ('time', 'Waktu', 'kanji'),
  ('nature', 'Alam', 'kanji'),
  ('numbers', 'Angka', 'kanji'),
  ('people', 'Orang', 'kanji'),
  ('actions', 'Aksi', 'kanji'),
  ('adjectives', 'Kata Sifat', 'kanji'),
  ('education', 'Pendidikan', 'kanji'),
  ('objects', 'Benda', 'kanji'),
  ('places', 'Tempat', 'kanji'),
  ('direction', 'Arah', 'kanji'),
  ('colors', 'Warna', 'kanji'),
  ('size', 'Ukuran & Jumlah', 'kanji'),
  -- Kosakata categories
  ('greetings', 'Sapaan', 'kosakata'),
  ('verbs', 'Kata Kerja', 'kosakata'),
  ('i-adjectives', 'Kata Sifat -i', 'kosakata'),
  ('na-adjectives', 'Kata Sifat -na', 'kosakata'),
  ('nouns', 'Kata Benda', 'kosakata'),
  -- Bunpo categories
  ('particles', 'Partikel', 'bunpo'),
  ('verb-forms', 'Bentuk Kata Kerja', 'bunpo'),
  ('conjunctions', 'Kata Penghubung', 'bunpo'),
  ('copula', 'Kopula', 'bunpo'),
  ('expressions', 'Ekspresi', 'bunpo'),
  -- Semantic Categories (New)
  ('family', 'Keluarga', 'kosakata'),
  ('food', 'Makanan & Minuman', 'kosakata'),
  ('time', 'Waktu', 'kosakata'),
  ('daily-life', 'Kehidupan Sehari-hari', 'kosakata'),
  ('nature', 'Alam & Cuaca', 'kosakata'),
  ('body', 'Tubuh & Kesehatan', 'kosakata'),
  ('transportation', 'Transportasi', 'kosakata'),
  ('places', 'Tempat & Bangunan', 'kosakata'),
  ('school', 'Sekolah & Pendidikan', 'kosakata'),
  ('occupation', 'Pekerjaan', 'kosakata'),
  ('clothing', 'Pakaian', 'kosakata'),
  ('house', 'Rumah & Perabot', 'kosakata'),
  ('colors', 'Warna', 'kosakata'),
  ('positions', 'Posisi & Arah', 'kosakata')
ON CONFLICT (slug) DO NOTHING;

-- ============================================
-- Table: kanji
-- ============================================
CREATE TABLE IF NOT EXISTS kanji (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  character VARCHAR(10) NOT NULL UNIQUE,
  meaning TEXT NOT NULL,
  onyomi TEXT,
  kunyomi TEXT,
  jlpt_level VARCHAR(2) REFERENCES jlpt_levels(id) ON DELETE SET NULL,
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  stroke_count INTEGER,
  examples JSONB DEFAULT '[]',
  sort_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Table: kosakata (vocabulary)
-- ============================================
CREATE TABLE IF NOT EXISTS kosakata (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  kanji TEXT NOT NULL UNIQUE, -- Formerly 'word'
  hiragana TEXT NOT NULL,     -- Formerly 'reading'
  romaji TEXT,                -- New column for ease of reading
  meaning TEXT NOT NULL,
  jlpt_level VARCHAR(2) REFERENCES jlpt_levels(id) ON DELETE SET NULL,
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  example_sentence TEXT,
  example_translation TEXT,
  related_kanji UUID[],
  audio_url TEXT,
  sort_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Table: bunpo (grammar + sentence patterns)
-- ============================================
CREATE TABLE IF NOT EXISTS bunpo (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  pattern TEXT NOT NULL,
  meaning TEXT NOT NULL,
  usage TEXT,
  bunpo_type VARCHAR(20) CHECK (bunpo_type IN ('grammar', 'sentence_pattern')) DEFAULT 'grammar',
  jlpt_level VARCHAR(2) REFERENCES jlpt_levels(id) ON DELETE SET NULL,
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  examples JSONB DEFAULT '[]',
  notes TEXT,
  sort_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Table: user_progress (user optional, support anonymous)
-- ============================================
CREATE TABLE IF NOT EXISTS user_progress (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- NULL for anonymous users
  anonymous_id TEXT, -- For users without account
  content_type VARCHAR(20) CHECK (content_type IN ('kanji', 'kosakata', 'bunpo')) NOT NULL,
  content_id UUID NOT NULL,
  mastery_level INTEGER DEFAULT 0 CHECK (mastery_level >= 0 AND mastery_level <= 5),
  last_reviewed TIMESTAMP WITH TIME ZONE,
  next_review TIMESTAMP WITH TIME ZONE,
  review_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  -- Either user_id OR anonymous_id must be set
  CONSTRAINT user_or_anon CHECK (user_id IS NOT NULL OR anonymous_id IS NOT NULL)
);

-- Unique indexes for user_progress (separate for logged-in and anonymous users)
CREATE UNIQUE INDEX IF NOT EXISTS idx_progress_user_unique 
  ON user_progress (user_id, content_type, content_id) 
  WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_progress_anon_unique 
  ON user_progress (anonymous_id, content_type, content_id) 
  WHERE anonymous_id IS NOT NULL;

-- ============================================
-- Table: admins
-- ============================================
CREATE TABLE IF NOT EXISTS admins (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Table: learning_days (for roadmap)
-- ============================================
CREATE TABLE IF NOT EXISTS learning_days (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  jlpt_level VARCHAR(2) REFERENCES jlpt_levels(id) ON DELETE CASCADE,
  day_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  estimated_minutes INTEGER DEFAULT 30,
  is_review_day BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(jlpt_level, day_number)
);

-- ============================================
-- Table: learning_day_topics (Group items by topic)
-- ============================================
CREATE TABLE IF NOT EXISTS learning_day_topics (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  learning_day_id UUID REFERENCES learning_days(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content_type VARCHAR(20) CHECK (content_type IN ('kanji', 'kosakata', 'bunpo')) NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Junction Tables: Topic Items (proper FK references!)
-- ============================================

-- Kanji items in a topic
CREATE TABLE IF NOT EXISTS learning_topic_kanji (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  topic_id UUID REFERENCES learning_day_topics(id) ON DELETE CASCADE,
  kanji_id UUID REFERENCES kanji(id) ON DELETE CASCADE,
  note TEXT, -- Tips/Fakta Unik/Contoh khusus untuk roadmap
  sort_order INTEGER DEFAULT 0,
  UNIQUE(topic_id, kanji_id)
);

-- Kosakata items in a topic
CREATE TABLE IF NOT EXISTS learning_topic_kosakata (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  topic_id UUID REFERENCES learning_day_topics(id) ON DELETE CASCADE,
  kosakata_id UUID REFERENCES kosakata(id) ON DELETE CASCADE,
  note TEXT,
  sort_order INTEGER DEFAULT 0,
  UNIQUE(topic_id, kosakata_id)
);

-- Bunpo items in a topic
CREATE TABLE IF NOT EXISTS learning_topic_bunpo (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  topic_id UUID REFERENCES learning_day_topics(id) ON DELETE CASCADE,
  bunpo_id UUID REFERENCES bunpo(id) ON DELETE CASCADE,
  note TEXT,
  sort_order INTEGER DEFAULT 0,
  UNIQUE(topic_id, bunpo_id)
);

-- ============================================
-- Indexes for performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_kanji_jlpt ON kanji(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_kanji_category ON kanji(category_id);
CREATE INDEX IF NOT EXISTS idx_kosakata_jlpt ON kosakata(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_kosakata_category ON kosakata(category_id);
CREATE INDEX IF NOT EXISTS idx_bunpo_jlpt ON bunpo(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_bunpo_type ON bunpo(bunpo_type);
CREATE INDEX IF NOT EXISTS idx_progress_user ON user_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_anon ON user_progress(anonymous_id);
CREATE INDEX IF NOT EXISTS idx_progress_next_review ON user_progress(next_review);
CREATE INDEX IF NOT EXISTS idx_learning_days_level ON learning_days(jlpt_level, day_number);
CREATE INDEX IF NOT EXISTS idx_day_topics_day ON learning_day_topics(learning_day_id);
CREATE INDEX IF NOT EXISTS idx_topic_kanji ON learning_topic_kanji(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_kosakata ON learning_topic_kosakata(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_bunpo ON learning_topic_bunpo(topic_id);

-- ============================================
-- Row Level Security (RLS)
-- ============================================
ALTER TABLE jlpt_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE kanji ENABLE ROW LEVEL SECURITY;
ALTER TABLE kosakata ENABLE ROW LEVEL SECURITY;
ALTER TABLE bunpo ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_days ENABLE ROW LEVEL SECURITY;

-- Public read access for content tables
DROP POLICY IF EXISTS "Public read jlpt_levels" ON jlpt_levels;
CREATE POLICY "Public read jlpt_levels" ON jlpt_levels FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read categories" ON categories;
CREATE POLICY "Public read categories" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read kanji" ON kanji;
CREATE POLICY "Public read kanji" ON kanji FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read kosakata" ON kosakata;
CREATE POLICY "Public read kosakata" ON kosakata FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read bunpo" ON bunpo;
CREATE POLICY "Public read bunpo" ON bunpo FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read learning_days" ON learning_days;
CREATE POLICY "Public read learning_days" ON learning_days FOR SELECT USING (true);

-- Security definer function to check admin status (avoids infinite recursion)
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM admins WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Admin write access using the security definer function
DROP POLICY IF EXISTS "Admin write kanji" ON kanji;
CREATE POLICY "Admin write kanji" ON kanji FOR ALL USING (is_admin());

DROP POLICY IF EXISTS "Admin write kosakata" ON kosakata;
CREATE POLICY "Admin write kosakata" ON kosakata FOR ALL USING (is_admin());

DROP POLICY IF EXISTS "Admin write bunpo" ON bunpo;
CREATE POLICY "Admin write bunpo" ON bunpo FOR ALL USING (is_admin());

DROP POLICY IF EXISTS "Admin write categories" ON categories;
CREATE POLICY "Admin write categories" ON categories FOR ALL USING (is_admin());

DROP POLICY IF EXISTS "Admin write learning_days" ON learning_days;
CREATE POLICY "Admin write learning_days" ON learning_days FOR ALL USING (is_admin());

-- User progress policies
DROP POLICY IF EXISTS "Users can view own progress" ON user_progress;
CREATE POLICY "Users can view own progress" ON user_progress 
  FOR SELECT USING (user_id = auth.uid() OR anonymous_id IS NOT NULL);

DROP POLICY IF EXISTS "Users can insert progress" ON user_progress;
CREATE POLICY "Users can insert progress" ON user_progress 
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update own progress" ON user_progress;
CREATE POLICY "Users can update own progress" ON user_progress 
  FOR UPDATE USING (user_id = auth.uid() OR anonymous_id IS NOT NULL);

-- Admins table: self-referencing policy (no recursion)
DROP POLICY IF EXISTS "Admins can view self" ON admins;
CREATE POLICY "Admins can view self" ON admins FOR SELECT 
  USING (id = auth.uid());

-- ============================================
-- Triggers for updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_kanji_updated_at BEFORE UPDATE ON kanji
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_kosakata_updated_at BEFORE UPDATE ON kosakata
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_bunpo_updated_at BEFORE UPDATE ON bunpo
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- View: Content with JLPT level info (optional)
-- ============================================
CREATE OR REPLACE VIEW kanji_with_level AS
SELECT 
  k.*,
  j.name as jlpt_name,
  j.color as jlpt_color,
  c.name as category_name,
  c.slug as category
FROM kanji k
LEFT JOIN jlpt_levels j ON k.jlpt_level = j.id
LEFT JOIN categories c ON k.category_id = c.id;

CREATE OR REPLACE VIEW kosakata_with_level AS
SELECT 
  k.*,
  j.name as jlpt_name,
  j.color as jlpt_color,
  c.name as category_name,
  c.slug as category
FROM kosakata k
LEFT JOIN jlpt_levels j ON k.jlpt_level = j.id
LEFT JOIN categories c ON k.category_id = c.id;

CREATE OR REPLACE VIEW bunpo_with_level AS
SELECT 
  b.*,
  j.name as jlpt_name,
  j.color as jlpt_color,
  c.name as category_name,
  c.slug as category
FROM bunpo b
LEFT JOIN jlpt_levels j ON b.jlpt_level = j.id
LEFT JOIN categories c ON b.category_id = c.id;
